{% set version = "2.0.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rxode2et
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2et_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2et/rxode2et_{{ version }}.tar.gz
  sha256: dccf627ffae76c607ae4fbdb2e8e98c353c4b6727f9e0c5994f1ef228d9ff9de

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-rcpp
    - r-rxode2parse >=2.0.19
    - r-rxode2random >=2.1.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-checkmate
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-rcpp
    - r-rxode2parse >=2.0.19
    - r-rxode2random >=2.1.1

test:
  commands:
    - $R -e "library('rxode2et')"           # [not win]
    - "\"%R%\" -e \"library('rxode2et')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2et/
  dev_url: https://github.com/nlmixr2/rxode2et/
  license: GPL-3.0-or-later
  summary: Provides the event table and support functions needed for 'rxode2' (Wang, Hallow and  James (2016) <doi:10.1002/psp4.12052>) and 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split will reduce computational burden of recompiling 'rxode2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
