{% set version = "2.0.12" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rxode2et
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2et_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2et/rxode2et_{{ version }}.tar.gz
  sha256: 6af548a7b60e889270b51858facefb4f17f4e0caa6df0f47ec9f3911c3e0121e

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-checkmate
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-rxode2parse >=2.0.17
    - r-rxode2random >=2.0.12
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-checkmate
    - r-cli
    - r-crayon
    - r-lotri
    - r-magrittr
    - r-rxode2parse >=2.0.17
    - r-rxode2random >=2.0.12

test:
  commands:
    - $R -e "library('rxode2et')"           # [not win]
    - "\"%R%\" -e \"library('rxode2et')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2et/
  dev_url: https://github.com/nlmixr2/rxode2et/
  license: GPL-3.0-or-later
  summary: Provides the event table and support functions needed for 'rxode2' (Wang, Hallow and  James (2016) <doi:10.1002/psp4.12052>) and 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split will reduce computational burden of recompiling 'rxode2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rxode2et
# Title: Event Table Functions for 'rxode2'
# Version: 2.0.10
# Authors@R: c( person("Matthew L.", "Fidler", , "matthew.fidler@gmail.com", role = c("aut", "cre"), comment = c(ORCIDf = "0000-0001-8538-6691")), person("Wenping", "Wang", , "wwang8198@gmail.com", role = "ctb"), person("Fuji", "Goro", email="gfuji@cpan.org", role="ctb"), person("Morwenn", "", role="ctb"), person("Igor", "Kushnir", email="igorkuo@gmail.com", role="ctb") )
# Description: Provides the event table and support functions needed for 'rxode2' (Wang, Hallow and  James (2016) <doi:10.1002/psp4.12052>) and 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split will reduce computational burden of recompiling 'rxode2'.
# License: GPL (>= 3)
# URL: https://nlmixr2.github.io/rxode2et/, https://github.com/nlmixr2/rxode2et/
# BugReports: https://github.com/nlmixr2/rxode2et/issues/
# Depends: R (>= 4.0.0)
# Imports: stats, utils, methods, Rcpp, checkmate, rxode2random, rxode2parse (> 2.0.13), cli, crayon, magrittr, lotri
# Suggests: testthat (>= 3.0.0), units, tibble, data.table, dplyr, pillar, nlmixr2data, qs
# LinkingTo: rxode2random, rxode2parse, Rcpp
# Biarch: true
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# NeedsCompilation: yes
# RoxygenNote: 7.2.1
# Packaged: 2023-03-17 19:48:52 UTC; matt
# Author: Matthew L. Fidler [aut, cre] (0000-0001-8538-6691), Wenping Wang [ctb], Fuji Goro [ctb], Morwenn [ctb], Igor Kushnir [ctb]
# Maintainer: Matthew L. Fidler <matthew.fidler@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-03-17 23:00:02 UTC
